set terminal pdf
set output 'NiO.bands.pdf'

set xrange[0:3.78577]
set yrange[-7:10]

set grid x
set axis y2 right linked y
set ylabel "E [eV]"

set title "LDA band structure of NiO"

#labels can be found in case.bands.agr generated by spaghetti
set xtics ("L" 0, "$\Gamma$" 0.69078, "X" 1.48843, "W" 1.88726, "L" 2.45128, "K" 2.93974, "$\Gamma$" 3.78577)
set y2ticks ("$E_F$" 0)

set key bottom xcenter 0.0, -1.7
set keycolumns 5

#colors for d orbitals
corb1 = rgb(0.0,0.682,0.937)
corb2 = rgb(1.0,0.769,0.145)
corb3 = rgb(0.898,0.094,0.212)
corb4 = rgb(0.0,0.165,0.361)
corb5 = rgb(0.478,0.757,0.259)
set palette corb1, corb2, corb3, corb4, corb5

a=0.6

plot 0 with lines lt 2 color grey notitle, \
     "NiO.bands" using 2:3 with lines color black lw 0.2 notitle, \
     "NiO.bands" using 2:3 with points color 1 ps $5*a pt 17 notitle, \
     "NiO.bands" using 2:3 with points color 2 ps $6*a pt 17 notitle, \
     "NiO.bands" using 2:3 with points color 3 ps $7*a pt 17 notitle, \
     "NiO.bands" using 2:3 with points color 4 ps $8*a pt 17 notitle, \
     "NiO.bands" using 2:3 with points color 5 ps $9*a pt 17 notitle, \
     -100 with points color 1 pt 17 title "Ni 3$d_{z^2}$", \
     -100 with points color 2 pt 17 title "Ni 3$d_{x^2 - y^2}$", \
     -100 with points color 3 pt 17 title "Ni 3$d_{xy}$", \
     -100 with points color 4 pt 17 title "Ni 3$d_{xz}$", \
     -100 with points color 5 pt 17 title "Ni 3$d_{yz}$"
     